app = "video-indirici"
primary_region = "ist"

[build]

[[services]]
  internal_port = 5000
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
